USE RHSENAI 
SELECT * FROM Funcionarios;

ALTER TABLE Funcionarios ADD
DATA_NASCIMENTO date,
SEXO varchar(10),
ENDERECO varchar(50),
COD_CARGO int,
CEP varchar(8);

ALTER TABLE Funcionarios DROP COLUMN CEP;

EXEC sp_rename 'Funcionarios.COD_FUNCIONARIO', 'COD_FUNC', 'COLUMN';

ALTER TABLE Funcionarios
ALTER COLUMN SALARIO DECIMAL(18,2);

ALTER TABLE Funcionarios
ADD CONSTRAINT PK_COD_FUNCIONARIO PRIMARY KEY(COD_FUNC);